#+TITLE: Notes
* Inbox
** [2021-04-07 Wed]  Off-grid living

- Straw bale wall construction
http://monumentmasonry.com/masonry-news/straw-bale-blunders-and-errors/straw-bale/


** [2021-03-19 Fri] Blockly :LIBRARY:INTERESTING:
We could consider using [[https://developers.google.com/blockly][blokcly]] as a builder interface. There's also a thin
Clojure wrapper called [[https://github.com/ParkerICI/blockoid][blockoid]]. Could use as interface for creating layouts
perhaps, if not everything. See also [[https://github.com/kloimhardt/clj-tiles][clj-tiles]] and [[https://kloimhardt.github.io/cljtiles.html?page=12][the demo]].

** [2021-03-19 Fri] Who are you doing this for :PHILOSOPHY:
I want to create a place can play simple games and talk, like
a family living room. A place where anyone can make a little game
to play with their fiends and family. A place to relax.

** [2021-03-19 Fri] Everything in small pieces. :PHILOSOPHY:
Chase small rewards everyday. Make sure you're solving problems at a daily rate. Never go more than a day without solving at least one problem. Recognize your limits

** [2021-03-15 Mon] Setting expectations: A timeline :RESEARCH:
There's a rambly but maybe interesting discussion [[https://brandonthegamedev.com/lets-set-expectations-time-money-effort/][here]]. Here's a tidbit:

Brandon: In regards to your first printed game, Go Fish Fitness, how long did it take you to make it?

Garret: From concept to fulfillment, 10 months…

- 1 month to finalize the initial design and prototype
- 2 weeks to contact and come to an agreement with an artist
- 1 month of vacation (he was on vacation, my wife and I were welcoming our most recent child into the world)
- 2.5 months to complete and finalize the artwork
- 1.5 months to prepare the print files, finalize the box art, and print sample production copies
- 1 month to prepare for the Kickstarter.
- 1 month to run the Kickstarter.
- 1.5 months to manufacture and distribute

** [2021-03-15 Mon] 5 Levels of Communication through Game Development :RESEARCH:

- Core Engine: minimum et of rules.
- Mechanics: Constraints that create obstacles.
- Rules: Regulate how mechanics are implemented (???) Meta mechanics? Principles?
- Internal Narrative: rags to riches, etc.
- External Narrative: sales pitch.

** [2021-03-15 Mon] Your first Board Game :RESEARCH:

https://brandonthegamedev.com/start-to-finish-publish-and-sell-your-first-board-game/

** [2021-03-15 Mon] Advice about working on first game :RESEARCH:

https://boardgamedesigncourse.com/advice-i-wish-i-had-when-i-was-working-on-my-first-game/

Take Away:

- Share your idea
- Show it to people! (feedback)
- playtesters!
- Work *consistently*!
- Don't worry about the first game!
  + This may mean that your first game is just an expansion or knockoff of an existing game.
  + It's good to have a portfolio demonstrating progression anyway

From the comments:
- Know why you are making the game.
  + Should we be trying to make money? Why not exactly?
