* Inbox
** [ ] Implement insert-chars
DEADLINE: <2021-03-24 Wed> SCHEDULED: <2021-03-23 Tue>
:LOGBOOK:
CLOCK: [2021-03-24 Wed 03:30]
:END:
Implement the cursor function ~insert-chars~. This function simply takes
a cursor and a string of text, and inserts the text as updates to existing
tokens or new additional tokens if necessary.

It may be worth breaking this into ~parse-tokens~ and ~insert-tokens~, where
~insert-tokens~ potentially unifies the first and last input tokens.
** [X] Try xdg-open-server
SCHEDULED: <2021-03-23 Tue>
:LOGBOOK:
CLOCK: [2021-03-23 Tue 13:00]--[2021-03-23 Tue 13:29] =>  0:00
:END:
Try to use [[https://github.com/kitsunyan/xdg-open-server][xdg-open-server]] to open links in host.

Conclusion: not immediately feasible. WSL2 is a strange beast.
** [X] Fix launch install
SCHEDULED: <2021-03-23 Tue>
:LOGBOOK:
CLOCK: [2021-03-23 Tue 11:09]--[2021-03-23 Tue 11:13] =>  0:02
:END:
** [X] Fix time in container
SCHEDULED: <2021-03-23 Tue>
:LOGBOOK:
CLOCK: [2021-03-23 Tue 11:00]--[2021-03-23 Tue 11:09] => -7:08
:END:

** [X] Try out NixOS on WSL 2.
SCHEDULED: <2021-03-23 Tue>
:LOGBOOK:
CLOCK: [2021-03-23 Tue 11:13]--[2021-03-23 Tue 11:20] =>  0:01
:END:
Found out WSL2 also does not support systemd natively. This is also not worth worrying about.
The above fix for time in container is satisfactory for now.

** [X] Write windows install instructions
SCHEDULED: <2021-03-23 Tue>
:LOGBOOK:
CLOCK: [2021-03-23 Tue 11:21]--[2021-03-23 Tue 12:46] =>  1:25
:END:

** DONE Get Sandbox running with Windows
SCHEDULED: <2021-03-18 Thu>
